name: Update Blog Posts
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  push:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Update README with latest posts
        run: |
          pip install requests
          python .github/scripts/update_blog_posts.py

      - name: Commit and push changes
        run: |
          git config --global user.name "gabe"
          git config --global user.email "gabriel.antunessoares@gmail.com"
          git add README.md
          git commit -m "Update latest blog posts" || echo "No changes to commit"
          git push
